---
# handlers file for post-install
- name: reStart service on centos
  service:
    name: chrony
    state: restarted
    enabled: yes
  when: ansible_distribution == 'Centos'

- name: reStart service on ubuntu
  service:
    name: ntp
    state: restarted
    enabled: yes
  when: ansible_distribution == 'Ubuntu'
