---
- name: Provisioning servers
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent
      yum:
        name: chrony
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install ntp agent
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Start service on centos
      service:
        name: chrony
        state: started
        enabled: yes
      when: ansible_distribution == 'Centos'

    - name: Start service on ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'
