---
- name:
  hosts: all
    #gather_facts: False
  tasks:
   - name: Print OS name
     debug:
       var: ansible_distribution
   - name: Print selinux mode
     debug:
       var: ansible_selinux_mode
   - name: Print RAM memory
     debug:
       var: ansible_memory_mb.real.free

   - name: Print Propcessor name
     debug:
       var: ansible_processor[2]
